# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


# SUBJECTS
animsci = Subject.create(:name => "Animal Science")
astro = Subject.create(:name => "Astronomy")
bio = Subject.create(:name => "Biology")
chem = Subject.create(:name => "Chemistry")
envsci = Subject.create(:name => "Environmental Science")
phys = Subject.create(:name => "Physics")
pymath = Subject.create(:name => "Programming for Mathematics")


# INTROS
# ANIMAL SCIENCE INTRO
animsci.intros.create(:title => "AnimSci-Welcome", :content => "This would be content for a welcome introduction.")
animsci.intros.create(:title => "AnimSci-Regular", :content => "This would be content for a regular introduction.")
animsci.intros.create(:title => "AnimSci-Final", :content => "This would be content for a final introduction.")

# ASTRONOMY INTRO
astro.intros.create(:title => "Astro-Welcome", :content => "This would be content for a welcome introduction.")
astro.intros.create(:title => "Astro-Regular", :content => "This would be content for a regular introduction.")
astro.intros.create(:title => "Astro-Final", :content => "This would be content for a final introduction.")

# BIOLOGY INTRO
bio.intros.create(:title => "Bio-Welcome", :content => "This would be content for a welcome introduction.")
bio.intros.create(:title => "Bio-Regular", :content => "This would be content for a regular introduction.")
bio.intros.create(:title => "Bio-Final", :content => "This would be content for a final introduction.")

# CHEMISTRY INTRO
chem.intros.create(:title => "Chm-Welcome", :content => "This would be content for a welcome introduction.")
chem.intros.create(:title => "Chm-Regular", :content => "This would be content for a regular introduction.")
chem.intros.create(:title => "Chm-Final", :content => "This would be content for a concluding introduction.")

# ENVIRONMENTAL SCIENCE INTRO
envsci.intros.create(:title => "EnvSci-Welcome", :content => "This would be content for a welcome introduction.")
envsci.intros.create(:title => "EnvSci-Regular", :content => "This would be content for a regular introduction.")
envsci.intros.create(:title => "EnvSci-Final", :content => "This would be content for a concluding introduction.")

# PHYSICS INTRO
phys.intros.create(:title => "Phys-Welcome", :content => "This would be content for a welcome introduction.")
phys.intros.create(:title => "Phys-Regular", :content => "This would be content for a regular introduction.")
phys.intros.create(:title => "Phys-Final", :content => "This would be content for a concluding introduction.")

# PYMATH INTRO
pymath.intros.create(:title => "PyMath-Welcome", :content => "This would be content for a welcome introduction.")
pymath.intros.create(:title => "PyMath-Regular", :content => "This would be content for a regular introduction.")
pymath.intros.create(:title => "PyMath-Final", :content => "This would be content for a concluding introduction.")

# UNITS
# ANIMAL SCIENCE UNITS


# ASTRONOMY UNITS


# BIOLOGY UNITS
bio.units.create(:title => "01-The Science of Biology", :content => "This would be valid content.")
bio.units.create(:title => "02-The Chemistry of Life", :content => "This would be valid content.")
bio.units.create(:title => "03-The Biosphere", :content => "This would be valid content.")
bio.units.create(:title => "04-Ecosystems and Communities", :content => "This would be valid content.")
bio.units.create(:title => "05-Populations", :content => "This would be valid content.")
bio.units.create(:title => "06-Humans in the Biosphere", :content => "This would be valid content.")
bio.units.create(:title => "07-Cell Structure and Function", :content => "This would be valid content.")
bio.units.create(:title => "08-Photosynthesis", :content => "This would be valid content.")
bio.units.create(:title => "09-Cellular Respiration", :content => "This would be valid content.")
bio.units.create(:title => "10-Cell Growth and Division", :content => "This would be valid content.")
bio.units.create(:title => "11-Introduction to Genetics", :content => "This would be valid content.")
bio.units.create(:title => "12-DNA and RNA", :content => "This would be valid content.")
bio.units.create(:title => "13-Genetic Engineering", :content => "This would be valid content.")
bio.units.create(:title => "14-The Human Genome", :content => "This would be valid content.")
bio.units.create(:title => "15-Darwins Theory of Evolution", :content => "This would be valid content.")
bio.units.create(:title => "16-Evolution of Populations", :content => "This would be valid content.")
bio.units.create(:title => "17-The History of Life", :content => "This would be valid content.")
bio.units.create(:title => "18-Classification", :content => "This would be valid content.")
bio.units.create(:title => "19-Bacteria and Viruses", :content => "This would be valid content.")
bio.units.create(:title => "20-Protists", :content => "This would be valid content.")
bio.units.create(:title => "21-Fungi", :content => "This would be valid content.")
bio.units.create(:title => "22-Plant Diversity", :content => "This would be valid content.")
bio.units.create(:title => "23-Roots Stems and Leaves", :content => "This would be valid content.")
bio.units.create(:title => "24-Reproduction of Seed Plants", :content => "This would be valid content.")
bio.units.create(:title => "25-Plant Responses and Adaptations", :content => "This would be valid content.")
bio.units.create(:title => "26-Sponges and Cnidarians", :content => "This would be valid content.")
bio.units.create(:title => "27-Worms and Mollusks", :content => "This would be valid content.")
bio.units.create(:title => "28-Arthropods and Echinoderms", :content => "This would be valid content.")
bio.units.create(:title => "29-Comparing Invertebrates", :content => "This would be valid content.")
bio.units.create(:title => "30-Nonvertebrate Chordates Fishes and Amphibians", :content => "This would be valid content.")
bio.units.create(:title => "31-Reptiles and Birds", :content => "This would be valid content.")
bio.units.create(:title => "32-Mammals", :content => "This would be valid content.")
bio.units.create(:title => "33-Comparing Chordates", :content => "This would be valid content.")
bio.units.create(:title => "34-Animal Behavior", :content => "This would be valid content.")
bio.units.create(:title => "35-Nervous System", :content => "This would be valid content.")
bio.units.create(:title => "36-Skeletal Muscular and Integumentary Systems", :content => "This would be valid content.")
bio.units.create(:title => "37-Circulatory and Respiratory Systems", :content => "This would be valid content.")
bio.units.create(:title => "38-Digestive and Excretory Systems", :content => "This would be valid content.")
bio.units.create(:title => "39-Endocrine and Reproductive Systems", :content => "This would be valid content.")
bio.units.create(:title => "40-The Immune System and Disease", :content => "This would be valid content.")

# CHEMISTRY UNITS
chem.units.create(:title => "01-Introduction to Chemistry", :content => "This would be valid content.")
chem.units.create(:title => "02-Matter and Change", :content => "This would be valid content.")
chem.units.create(:title => "03-Scientific Measurement", :content => "This would be valid content.")
chem.units.create(:title => "04-Atomic Structure", :content => "This would be valid content.")
chem.units.create(:title => "05-Electrons in Atoms", :content => "This would be valid content.")
chem.units.create(:title => "06-The Periodic Table", :content => "This would be valid content.")
chem.units.create(:title => "07-Ionic and Metallic Bonding", :content => "This would be valid content.")
chem.units.create(:title => "08-Covalent Bonding", :content => "This would be valid content.")
chem.units.create(:title => "09-Chemical Names and Formulas", :content => "This would be valid content.")
chem.units.create(:title => "10-Chemical Quantities", :content => "This would be valid content.")
chem.units.create(:title => "11-Chemical Reactions", :content => "This would be valid content.")
chem.units.create(:title => "12-Stoichiometry", :content => "This would be valid content.")
chem.units.create(:title => "13-States of Matter", :content => "This would be valid content.")
chem.units.create(:title => "14-The Behavior of Gases", :content => "This would be valid content.")
chem.units.create(:title => "15-Water and Aqueous Systems", :content => "This would be valid content.")
chem.units.create(:title => "16-Solutions", :content => "This would be valid content.")
chem.units.create(:title => "17-Thermochemistry", :content => "This would be valid content.")
chem.units.create(:title => "18-Reaction Rates and Equilibrium", :content => "This would be valid content.")
chem.units.create(:title => "19-Acids Bases and Salts", :content => "This would be valid content.")
chem.units.create(:title => "20-Oxidation-Reduction Reactions", :content => "This would be valid content.")
chem.units.create(:title => "21-Electrochemistry", :content => "This would be valid content.")
chem.units.create(:title => "22-Hydrocarbon Compounds", :content => "This would be valid content.")
chem.units.create(:title => "23-Functional Groups", :content => "This would be valid content.")
chem.units.create(:title => "24-The Chemistry of Life", :content => "This would be valid content.")
chem.units.create(:title => "25-Nuclear Chemistry", :content => "This would be valid content.")

# ENVIRONMENTAL SCIENCE UNITS
envsci.units.create(:title => "01-Science and the Environment", :content => "This would be valid content.")
envsci.units.create(:title => "02-Tools of Environmental Science", :content => "This would be valid content.")
envsci.units.create(:title => "03-The Dynamic Earth", :content => "This would be valid content.")
envsci.units.create(:title => "04-The Organization of Life", :content => "This would be valid content.")
envsci.units.create(:title => "05-How Ecosystems Work", :content => "This would be valid content.")
envsci.units.create(:title => "06-Biomes", :content => "This would be valid content.")
envsci.units.create(:title => "07-Aquatic Ecosystems", :content => "This would be valid content.")
envsci.units.create(:title => "08-Understanding Populations", :content => "This would be valid content.")
envsci.units.create(:title => "09-The Human Population", :content => "This would be valid content.")
envsci.units.create(:title => "10-Biodiversity", :content => "This would be valid content.")
envsci.units.create(:title => "11-Water", :content => "This would be valid content.")
envsci.units.create(:title => "12-Air", :content => "This would be valid content.")
envsci.units.create(:title => "13-Atmosphere and Climate Change", :content => "This would be valid content.")
envsci.units.create(:title => "14-Land", :content => "This would be valid content.")
envsci.units.create(:title => "15-Food and Agriculture", :content => "This would be valid content.")
envsci.units.create(:title => "16-Mining and Mineral Resources", :content => "This would be valid content.")
envsci.units.create(:title => "17-Nonrenewable Energy", :content => "This would be valid content.")
envsci.units.create(:title => "18-Renewable Energy", :content => "This would be valid content.")
envsci.units.create(:title => "19-Waste", :content => "This would be valid content.")
envsci.units.create(:title => "20-Environment and Human", :content => "This would be valid content.")
envsci.units.create(:title => "21-Economics Policy and the Future", :content => "This would be valid content.")

# PHYSICS UNITS
phys.units.create(:title => "01-About Science", :content => "This would be valid content.")
phys.units.create(:title => "02-Mechanical Equilibrium", :content => "This would be valid content.")
phys.units.create(:title => "03-Newtons First Law of Motion-Inertia", :content => "This would be valid content.")
phys.units.create(:title => "04-Linear Motion", :content => "This would be valid content.")
phys.units.create(:title => "05-Projectile Motion", :content => "This would be valid content.")
phys.units.create(:title => "06-Newtons Second Law of Motion-Force and Acceleration", :content => "This would be valid content.")
phys.units.create(:title => "07-Newtons Third Law of Motion-Action and Reaction", :content => "This would be valid content.")
phys.units.create(:title => "08-Momentum", :content => "This would be valid content.")
phys.units.create(:title => "09-Energy", :content => "This would be valid content.")
phys.units.create(:title => "10-Circular Motion", :content => "This would be valid content.")
phys.units.create(:title => "11-Rotational Equilibrium", :content => "This would be valid content.")
phys.units.create(:title => "12-Rotational Motion", :content => "This would be valid content.")
phys.units.create(:title => "13-Universal Gravitation", :content => "This would be valid content.")
phys.units.create(:title => "14-Satellite Motion", :content => "This would be valid content.")
phys.units.create(:title => "15-Special Relativity-Space and Time", :content => "This would be valid content.")
phys.units.create(:title => "16-Relativity-Momentum Mass Energy and Gravity", :content => "This would be valid content.")
phys.units.create(:title => "17-The Atomic Nature of Matter", :content => "This would be valid content.")
phys.units.create(:title => "18-Solids", :content => "This would be valid content.")
phys.units.create(:title => "19-Liquids", :content => "This would be valid content.")
phys.units.create(:title => "20-Gases", :content => "This would be valid content.")
phys.units.create(:title => "21-Temperature Heat and Expansion", :content => "This would be valid content.")
phys.units.create(:title => "22-Heat Transfer", :content => "This would be valid content.")
phys.units.create(:title => "23-Change of Phase", :content => "This would be valid content.")
phys.units.create(:title => "24-Thermodynamics", :content => "This would be valid content.")
phys.units.create(:title => "25-Vibrations and Waves", :content => "This would be valid content.")
phys.units.create(:title => "26-Sound", :content => "This would be valid content.")
phys.units.create(:title => "27-Light", :content => "This would be valid content.")
phys.units.create(:title => "28-Color", :content => "This would be valid content.")
phys.units.create(:title => "29-Reflection and Refraction", :content => "This would be valid content.")
phys.units.create(:title => "30-Lenses", :content => "This would be valid content.")
phys.units.create(:title => "31-Diffraction and Interference", :content => "This would be valid content.")
phys.units.create(:title => "32-Electrostatics", :content => "This would be valid content.")
phys.units.create(:title => "33-Electric Fields and Potential", :content => "This would be valid content.")
phys.units.create(:title => "34-Electric Current", :content => "This would be valid content.")
phys.units.create(:title => "35-Electric Circuits", :content => "This would be valid content.")
phys.units.create(:title => "36-Magnetism", :content => "This would be valid content.")
phys.units.create(:title => "37-Electromagnetic Induction", :content => "This would be valid content.")
phys.units.create(:title => "38-The Atom and The Quantum", :content => "This would be valid content.")
phys.units.create(:title => "39-The Atomic Nucleus and Radioactivity", :content => "This would be valid content.")
phys.units.create(:title => "40-Nuclear Fission and Fusion", :content => "This would be valid content.")

# PYMATH UNITS



# FUTURES
# ANIMAL SCIENCE FUTURES


# ASTRONOMY FUTURES


# BIOLOGY FUTURES
bio.futures.create(:title => "01-The Science of Biology", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "02-The Chemistry of Life", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "03-The Biosphere", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "04-Ecosystems and Communities", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "05-Populations", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "06-Humans in the Biosphere", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "07-Cell Structure and Function", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "08-Photosynthesis", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "09-Cellular Respiration", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "10-Cell Growth and Division", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "11-Introduction to Genetics", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "12-DNA and RNA", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "13-Genetic Engineering", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "14-The Human Genome", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "15-Darwins Theory of Evolution", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "16-Evolution of Populations", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "17-The History of Life", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "18-Classification", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "19-Bacteria and Viruses", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "20-Protists", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "21-Fungi", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "22-Plant Diversity", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "23-Roots Stems and Leaves", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "24-Reproduction of Seed Plants", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "25-Plant Responses and Adaptations", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "26-Sponges and Cnidarians", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "27-Worms and Mollusks", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "28-Arthropods and Echinoderms", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "29-Comparing Invertebrates", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "30-Nonvertebrate Chordates Fishes and Amphibians", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "31-Reptiles and Birds", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "32-Mammals", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "33-Comparing Chordates", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "34-Animal Behavior", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "35-Nervous System", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "36-Skeletal Muscular and Integumentary Systems", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "37-Circulatory and Respiratory Systems", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "38-Digestive and Excretory Systems", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "39-Endocrine and Reproductive Systems", :content => "This would be valid content for what student will do.")
bio.futures.create(:title => "40-The Immune System and Disease", :content => "This would be valid content for what student will do.")

# CHEMISTRY FUTURES
chem.futures.create(:title => "01-Introduction to Chemistry", :content => "This would be valid content.")
chem.futures.create(:title => "02-Matter and Change", :content => "This would be valid content.")
chem.futures.create(:title => "03-Scientific Measurement", :content => "This would be valid content.")
chem.futures.create(:title => "04-Atomic Structure", :content => "This would be valid content.")
chem.futures.create(:title => "05-Electrons in Atoms", :content => "This would be valid content.")
chem.futures.create(:title => "06-The Periodic Table", :content => "This would be valid content.")
chem.futures.create(:title => "07-Ionic and Metallic Bonding", :content => "This would be valid content.")
chem.futures.create(:title => "08-Covalent Bonding", :content => "This would be valid content.")
chem.futures.create(:title => "09-Chemical Names and Formulas", :content => "This would be valid content.")
chem.futures.create(:title => "10-Chemical Quantities", :content => "This would be valid content.")
chem.futures.create(:title => "11-Chemical Reactions", :content => "This would be valid content.")
chem.futures.create(:title => "12-Stoichiometry", :content => "This would be valid content.")
chem.futures.create(:title => "13-States of Matter", :content => "This would be valid content.")
chem.futures.create(:title => "14-The Behavior of Gases", :content => "This would be valid content.")
chem.futures.create(:title => "15-Water and Aqueous Systems", :content => "This would be valid content.")
chem.futures.create(:title => "16-Solutions", :content => "This would be valid content.")
chem.futures.create(:title => "17-Thermochemistry", :content => "This would be valid content.")
chem.futures.create(:title => "18-Reaction Rates and Equilibrium", :content => "This would be valid content.")
chem.futures.create(:title => "19-Acids Bases and Salts", :content => "This would be valid content.")
chem.futures.create(:title => "20-Oxidation-Reduction Reactions", :content => "This would be valid content.")
chem.futures.create(:title => "21-Electrochemistry", :content => "This would be valid content.")
chem.futures.create(:title => "22-Hydrocarbon Compounds", :content => "This would be valid content.")
chem.futures.create(:title => "23-Functional Groups", :content => "This would be valid content.")
chem.futures.create(:title => "24-The Chemistry of Life", :content => "This would be valid content.")
chem.futures.create(:title => "25-Nuclear Chemistry", :content => "This would be valid content.")


# ENVIRONMENTAL SCIENCE FUTURES
envsci.futures.create(:title => "01-Science and the Environment", :content => "This would be valid content.")
envsci.futures.create(:title => "02-Tools of Environmental Science", :content => "This would be valid content.")
envsci.futures.create(:title => "03-The Dynamic Earth", :content => "This would be valid content.")
envsci.futures.create(:title => "04-The Organization of Life", :content => "This would be valid content.")
envsci.futures.create(:title => "05-How Ecosystems Work", :content => "This would be valid content.")
envsci.futures.create(:title => "06-Biomes", :content => "This would be valid content.")
envsci.futures.create(:title => "07-Aquatic Ecosystems", :content => "This would be valid content.")
envsci.futures.create(:title => "08-Understanding Populations", :content => "This would be valid content.")
envsci.futures.create(:title => "09-The Human Population", :content => "This would be valid content.")
envsci.futures.create(:title => "10-Biodiversity", :content => "This would be valid content.")
envsci.futures.create(:title => "11-Water", :content => "This would be valid content.")
envsci.futures.create(:title => "12-Air", :content => "This would be valid content.")
envsci.futures.create(:title => "13-Atmosphere and Climate Change", :content => "This would be valid content.")
envsci.futures.create(:title => "14-Land", :content => "This would be valid content.")
envsci.futures.create(:title => "15-Food and Agriculture", :content => "This would be valid content.")
envsci.futures.create(:title => "16-Mining and Mineral Resources", :content => "This would be valid content.")
envsci.futures.create(:title => "17-Nonrenewable Energy", :content => "This would be valid content.")
envsci.futures.create(:title => "18-Renewable Energy", :content => "This would be valid content.")
envsci.futures.create(:title => "19-Waste", :content => "This would be valid content.")
envsci.futures.create(:title => "20-Environment and Human", :content => "This would be valid content.")
envsci.futures.create(:title => "21-Economics Policy and the Future", :content => "This would be valid content.")

# PHYSICS FUTURES
phys.futures.create(:title => "01-About Science", :content => "This would be valid content.")
phys.futures.create(:title => "02-Mechanical Equilibrium", :content => "This would be valid content.")
phys.futures.create(:title => "03-Newtons First Law of Motion-Inertia", :content => "This would be valid content.")
phys.futures.create(:title => "04-Linear Motion", :content => "This would be valid content.")
phys.futures.create(:title => "05-Projectile Motion", :content => "This would be valid content.")
phys.futures.create(:title => "06-Newtons Second Law of Motion-Force and Acceleration", :content => "This would be valid content.")
phys.futures.create(:title => "07-Newtons Third Law of Motion-Action and Reaction", :content => "This would be valid content.")
phys.futures.create(:title => "08-Momentum", :content => "This would be valid content.")
phys.futures.create(:title => "09-Energy", :content => "This would be valid content.")
phys.futures.create(:title => "10-Circular Motion", :content => "This would be valid content.")
phys.futures.create(:title => "11-Rotational Equilibrium", :content => "This would be valid content.")
phys.futures.create(:title => "12-Rotational Motion", :content => "This would be valid content.")
phys.futures.create(:title => "13-Universal Gravitation", :content => "This would be valid content.")
phys.futures.create(:title => "14-Satellite Motion", :content => "This would be valid content.")
phys.futures.create(:title => "15-Special Relativity-Space and Time", :content => "This would be valid content.")
phys.futures.create(:title => "16-Relativity-Momentum Mass Energy and Gravity", :content => "This would be valid content.")
phys.futures.create(:title => "17-The Atomic Nature of Matter", :content => "This would be valid content.")
phys.futures.create(:title => "18-Solids", :content => "This would be valid content.")
phys.futures.create(:title => "19-Liquids", :content => "This would be valid content.")
phys.futures.create(:title => "20-Gases", :content => "This would be valid content.")
phys.futures.create(:title => "21-Temperature Heat and Expansion", :content => "This would be valid content.")
phys.futures.create(:title => "22-Heat Transfer", :content => "This would be valid content.")
phys.futures.create(:title => "23-Change of Phase", :content => "This would be valid content.")
phys.futures.create(:title => "24-Thermodynamics", :content => "This would be valid content.")
phys.futures.create(:title => "25-Vibrations and Waves", :content => "This would be valid content.")
phys.futures.create(:title => "26-Sound", :content => "This would be valid content.")
phys.futures.create(:title => "27-Light", :content => "This would be valid content.")
phys.futures.create(:title => "28-Color", :content => "This would be valid content.")
phys.futures.create(:title => "29-Reflection and Refraction", :content => "This would be valid content.")
phys.futures.create(:title => "30-Lenses", :content => "This would be valid content.")
phys.futures.create(:title => "31-Diffraction and Interference", :content => "This would be valid content.")
phys.futures.create(:title => "32-Electrostatics", :content => "This would be valid content.")
phys.futures.create(:title => "33-Electric Fields and Potential", :content => "This would be valid content.")
phys.futures.create(:title => "34-Electric Current", :content => "This would be valid content.")
phys.futures.create(:title => "35-Electric Circuits", :content => "This would be valid content.")
phys.futures.create(:title => "36-Magnetism", :content => "This would be valid content.")
phys.futures.create(:title => "37-Electromagnetic Induction", :content => "This would be valid content.")
phys.futures.create(:title => "38-The Atom and The Quantum", :content => "This would be valid content.")
phys.futures.create(:title => "39-The Atomic Nucleus and Radioactivity", :content => "This would be valid content.")
phys.futures.create(:title => "40-Nuclear Fission and Fusion", :content => "This would be valid content.")
# PYMATH FUTURES



# REPORTS
Report.create(:name => "Jimmy Jones", :comment => "Some personal Comments", :gender => "male", :classwork => "35", :assessment => "36", :participate => "37", :subject_id => 1, :initial_id => 1, :ending_id => 3, :intro_id => 1, :future_id => 3, :honor => true, :accel => true, :maxonline => true)

Report.create(:name => "Susie Stone", :comment => "Some personal Comments", :gender => "female", :classwork => "53", :assessment => "54", :participate => "55", :subject_id => 2, :initial_id => 4, :ending_id => 6, :intro_id => 4, :future_id => 6, :honor => false, :accel => false, :maxonline => false)
#
